version: '3.7'

services:
  mongodb_container:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: beanie
      MONGODB_PASSWORD: beanie
      MONGODB_DATABASE: beanie_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
