name: MyPy
on: [ pull_request ]

jobs:
  mypy:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.10.5 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: mypy install
        run: pip3 install mypy types-click types-toml
      - name: mypy
        run: mypy beanie/ tests/typing --config-file pyproject.toml
